# Generated by Django 5.0.7 on 2024-07-13 20:50

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('source_address', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_address', models.CharField(blank=True, max_length=200, null=True)),
                ('total_distance', models.FloatField(default=0)),
                ('extra_kms', models.FloatField(default=0)),
                ('extra_hours', models.FloatField(default=0)),
                ('rate_days', models.FloatField(default=0)),
                ('rate_km', models.FloatField(default=0)),
                ('rate_hours', models.FloatField(default=0)),
                ('running_days', models.FloatField(default=0)),
                ('running_kms', models.FloatField(default=0)),
                ('running_hrs', models.FloatField(default=0)),
                ('total_gross_value_days', models.FloatField(default=0)),
                ('total_gross_value_kms', models.FloatField(default=0)),
                ('total_gross_value_hrs', models.FloatField(default=0)),
                ('igst_days', models.FloatField(default=0)),
                ('igst_kms', models.FloatField(default=0)),
                ('igst_extra_hrs', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_gross_value_without_penalty', models.FloatField(default=0)),
                ('total_gross_value_after_penalty', models.FloatField(default=0)),
                ('total_deduction', models.FloatField(default=0)),
                ('cgst', models.FloatField(default=0)),
                ('igst', models.FloatField(default=0)),
                ('total_taxable_value', models.FloatField(default=0)),
                ('toll_and_parking', models.FloatField(default=0)),
                ('round_off', models.FloatField(default=0)),
                ('net_invoice_value', models.FloatField(default=0)),
                ('grand_total_in_words', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_in', models.CharField(blank=True, max_length=50, null=True)),
                ('team_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_in', models.CharField(max_length=40)),
                ('serial_number_of_invoice', models.CharField(max_length=40)),
                ('bill_to', models.CharField(max_length=200)),
                ('ship_to', models.CharField(max_length=200)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=services.models.Customer, to='services.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.state'),
        ),
    ]
