# Generated by Django 5.1 on 2024-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='team_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_extra_hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_kms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_percentage',
            field=models.FloatField(default=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_allowance',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='igst_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='igst_percentage',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='night_hold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='night_hold_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_extra_hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_kms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_percentage',
            field=models.FloatField(default=6),
        ),
        migrations.AddField(
            model_name='customer',
            name='destination_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Arunanchal Pradesh', 'Arunanchal Pradesh'), ('Gujarat', 'Gujarat')], default='Bihar', max_length=50),
        ),
    ]
