# Generated by Django 5.0.7 on 2024-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_booking_driver_allowance_booking_night_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cgst_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='igst_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sgst',
            field=models.FloatField(default=0),
        ),
    ]
