# Generated by Django 5.0.7 on 2024-08-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_booking_cgst_applicable_booking_igst_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cgst_percentage',
            field=models.FloatField(default=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='igst_percentage',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_percentage',
            field=models.FloatField(default=6),
        ),
    ]
