# Generated by Django 5.0.7 on 2024-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_booking_cgst_percentage_booking_igst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cgst_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_extra_hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cgst_kms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_extra_hrs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='sgst_kms',
            field=models.FloatField(default=0),
        ),
    ]
